from services.database.database import *
from services.settings.base import *
from services.registration import registrate
from services.authorization import authorize
from services.computering import compit
from services.computering import all_pcs
from services.carting import carte
from services.carting import all_user_carts
from services.carting import delete_cart
